#   ╔╗ ┌─┐┌─┐┌┬┐  ╦  ╦┬┌─┐┬ ┬  ╔╦╗┬┌─┐┌┬┐┌─┐┌┐┌┌─┐┌─┐
#   ╠╩╗├┤ └─┐ │   ╚╗╔╝│├┤ │││   ║║│└─┐ │ ├─┤││││  ├┤
#   ╚═╝└─┘└─┘ ┴    ╚╝ ┴└─┘└┴┘  ═╩╝┴└─┘ ┴ ┴ ┴┘└┘└─┘└─┘
#       - Get a Better View Distance, By LXCT. -

Version: 2.0

Features:
  UseAFKView: true
  UsePing: true
  UseTasks: true
  UseFlyingView: false
  UseTeleportView: false

ViewDistance:
  Min: 4
  Max: 16
  AFK: 3
  OnLogin: 4
  OnTeleport: 4
  OnFlying: 12
  MoreThanSettings: 0

Delay:
  UnsetTeleportViewDelay: 3
  CheckFlyingDelay: 5
  CalculationsDelay: 1
  SetViewDelay: 15
  AFKDelay: 90

Settings:
  PingForReduction: 550
  PingForAugmentation: 90
  TpsLimit: 19.5
  TpsChangeIndice: 0.01
  MaxReductionIndice: 0.75
  SafePing: 1

Misc:
  HideVdistLine4: false
  CheckUpdates: true
  Metrics: true