name: BestViewDistance
version: 1.0
api-version: 1.13
description: Best View Distance. Optimize your view distance.
author: Lxct
main: me.lxct.bestviewdistance.main

commands:
  view:
    description: Best View Distance Interface
    permission: view.check
    permission-message:

permissions:
  view.check:
    description: /view
    default: op