name: BestViewDistance
version: 7
api-version: 1.13
description: Best View Distance. Optimize your view distance.
author: Lxct
softdepend: [ProtocolLib]
main: me.lxct.bestviewdistance.BestViewDistance

commands:
  view:
    description: Best View Distance Interface
    permission: view
  vdist:
    description: Best View Distance Interface
    permission: view.info

permissions:
  view.update:
    description: Check the update of the plugins
    default: op
  view.check:
    description: Check players and reduction indice
    default: op
  view.info:
    description: Use /vdist to get your own view distance
    default: op
  view.set:
    description: Use /vdist to get your own view distance
    default: op
  view.reload:
    description: Reload BestViewDistance
    default: op