name: BestViewDistance
version: 4.0
api-version: 1.13
description: Best View Distance. Optimize your view distance.
author: Lxct
main: me.lxct.bestviewdistance.BestViewDistance

commands:
  view:
    description: Best View Distance Interface
    permission: view
  vdist:
    description: Best View Distance Interface
    permission: view.info

permissions:
  view.check:
    description: /view
    default: op
  view.info:
    description: /ve
    default: op
  view.reload:
    description: /view
    default: op