name: BestViewDistance
version: 1.0
api-version: 1.13
description: Best View Distance. Optimize your view distance.
author: Lxct
main: me.lxct.bestviewdistance.main

commands:
  mute:
    description: Mute un joueur.
    permission: mute.mute
    permission-message:

permissions:
  mute.mute:
    description: /mute
    default: op